modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"
[[mods]] #mandatory
modId="momoweave" #mandatory
version="1.0" #mandatory
displayName="Momoweave" #mandatory
authors="Mikul" #optional

description='''${mod_description}'''
[[dependencies."momoweave"]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="${forge_version_range}" #mandatory
   ordering="NONE"
   side="BOTH"# Here's another dependency
[[dependencies."momoweave"]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
